In [22]:
import pandas as pd

df = pd.read_csv("https://github.com/ellimilial/clinical-trials-negative-efficacy/raw/refs/heads/main/01-all-clinical-trials.csv.zip")
print(f"Loaded a total of {len(set(df.nct_id))} trials")
print(f"  - {len(df)} trial-intervention-condition")
print(f"  - {len(set(df.condition_name))} conditions")
print(f"  - {len(set(df.intervention_name))} interventions")

df.describe()

Loaded a total of 582141 trials
  - 1944960 trial-intervention-condition
  - 129379 conditions
  - 513773 interventions

,nct_id,brief_title,official_title,overall_status,start_date,completion_date,study_type,phase,why_stopped,condition_name,intervention_name,intervention_type
count,1944960,1944960,1920708,1944960,1933161,1874901,1943989,900713,177518,1943950,1835012,1835284
unique,582141,579644,568025,14,9212,10310,3,7,32998,129378,513772,11
top,NCT03878524,Serial Measurements of Molecular and Architect...,Serial Measurements of Molecular and Architect...,COMPLETED,2014-01-31,2026-12-31,INTERVENTIONAL,PHASE2,Low accrual,Healthy,Placebo,DRUG
freq,2800,2800,2800,990709,6317,32590,1623356,298082,3869,21875,53986,686124

In [32]:
# Only evaluate stopping reasons where we can link to both condition and intervention.
df_filtered = df[pd.notna(df["why_stopped"]) & pd.notna(df["condition_name"]) & pd.notna(df["intervention_name"])]
# Since the model was trained on case-sensitive data we should not be collapsing by case.
df_filtered["why_stopped"].drop_duplicates().reset_index(drop=True)

0                               Replaced by another study.
1          Study never opened; never enrolled participants
2                       Original P.I. left the institution
3            Unable to recruit adequate number of subjects
4                                  Study was never funded.
                               ...
31114     etik onay alındığı tarihte yapıldı ve tamamlandı
31115    Participant recruitment has been stopped becau...
31116    This study has been transferred to the Human R...
31117    Recruitment was temporarily suspended pending ...
31118    Operational decision not to proceed at this st...
Name: why_stopped, Length: 31119, dtype: object

,nct_id,brief_title,official_title,overall_status,start_date,completion_date,study_type,phase,why_stopped,condition_name,intervention_name,intervention_type
4208,NCT00001080,Effect of Vaccination on Turnover of Lamivudin...,Effect of Vaccination on Turnover of Lamivudin...,WITHDRAWN,NaN,NaN,INTERVENTIONAL,NaN,as of 4/23/97,HIV Infections,Influenza Virus Vaccine,BIOLOGICAL
4209,NCT00001080,Effect of Vaccination on Turnover of Lamivudin...,Effect of Vaccination on Turnover of Lamivudin...,WITHDRAWN,NaN,NaN,INTERVENTIONAL,NaN,as of 4/23/97,HIV Infections,Lamivudine,DRUG
4210,NCT00001080,Effect of Vaccination on Turnover of Lamivudin...,Effect of Vaccination on Turnover of Lamivudin...,WITHDRAWN,NaN,NaN,INTERVENTIONAL,NaN,as of 4/23/97,HIV Infections,"Pneumococcal Vaccine, Polyvalent (23-valent)",BIOLOGICAL

In [ ]:
df[pd.notna(df["condition_name"]) & pd.notna(df["why_stopped"]) & pd.notna(df["intervention_name"])]

In [ ]:
df[pd.notna(df["condition_name"]) & pd.notna(df["why_stopped"]) & pd.notna(df["intervention_name"])]

In [ ]:
df[df.nct_id == 'NCT00006321']

In [ ]:
df[pd.notna(df["condition_name"]) & pd.notna(df["why_stopped"])].why_stopped.nunique()

In [ ]:
# Verify the coverage against
df_ot = pd.read_csv("https://raw.githubusercontent.com/opentargets/stopReasons/main/data/stopped_predictions_formatted_30_09_22.csv")
print("In the OT set, t")
df_ot

In [ ]:
len(set(df_ot.nctid))